### ISSUE TITLE
mini cart doesnot work in rwd theme

### ISSUE THREAD

**Issue by purvi123** [husseycoding/ajaxcartpopup#3]
Hello,

mini cart doesnot work in rwd theme.

**Comment by husseycoding** [comment]
Can you give me some more specific detail?  At last time of testing it was working correctly with the RWD theme.

**Comment by purvi123** [comment]
Hello,
Mini cart is working only product detail page.any other pages is not working.

**Comment by husseycoding** [comment]
Are you using a clean, completely unmodified install running the extension and seeing the issue here?

**Comment by purvi123** [comment]
yes i installed extension from magentocommerce.

**Comment by husseycoding** [comment]
Not the extension, your magento install, is it completely unmodified?

**Comment by purvi123** [comment]
yes..

**Comment by husseycoding** [comment]
What is the URL for your site please?

**Comment by purvi123** [comment]
http://thebigindian.magentoprojects.net/

**Comment by husseycoding** [comment]
That's not an unmodified Magento install, it's been developed, and skinned.  You need to test on a clean unmodified install like Magento the demo site and see if you find an issue there.

**Comment by purvi123** [comment]
ok.thanks for your reply.i will try and inform you.

**Comment by purvi123** [comment]
hello,
i try extension in fresh magento in local but its also not working on cart page and checkout page.

**Comment by husseycoding** [comment]
Ah right, you didn't say you were referring just to the cart and checkout pages.  It's by design that the mini cart popup doesn't show here - no logic in showing a mini cart on the cart page or checkout when they both show the cart contents.

If you want to enable functionality on the cart and checkout pages you can edit the layout to remove the declarations which disable functionality:

    <update handle="disable_ajaxcartpopup" />

Note that if you do this, neither the cart nor the checkout pages will update if you edit cart contents or remove items from the cart popup, you'll need to customise functionality yourself to do this.  Note that the extension already adds AJAX functionality to the cart page.
