### ISSUE TITLE
Not working on a custom theme (1.9.2)

### ISSUE THREAD

**Issue by Dneiz** [husseycoding/ajaxcartpopup#45]
Hi,

Thank you for this awesome module.

Unfortunately it is not working optimum on my custom theme. (Works fine on the RWD theme). I use magento 1.9.2.

When you click on the cart, a gray line shows up, but not the mini-cart.
Can you help me please? It is for my client.

Jon (husseycoding) stated to make changes in the "CartController.php" file. Where do I need to make the changes?

Link testenvironment:
~~~

Thank you all!

**Comment by husseycoding** [comment]
Because your header cart is customised, the HTML in that area is not correct when it get's updated after adding to the cart.  So if you have a look at the controller file method [here](https://github.com/husseycoding/ajaxcartpopup/blob/master/app/code/community/HusseyCoding/AjaxCartPopup/controllers/CartController.php#L178), this is where the header link text is generated.  You can see that all of the header cart link contents is expected to be inside expects to an anchor element with class skip-cart or top-link-cart.  You have this element in this theme, but the only thing inside it is the cart icon graphic, not the cart count, price etc.

The text string created here is sent back in response to the AJAX request and is pulled in the JS file [here](https://github.com/husseycoding/ajaxcartpopup/blob/master/skin/frontend/base/default/js/ajaxcartpopup.js#L209), and the anchor element is updated [here](https://github.com/husseycoding/ajaxcartpopup/blob/master/skin/frontend/base/default/js/ajaxcartpopup.js#L261).

So you need to either rework these sections of code to work with your pages HTML structure, or alter the pages HTML structure to work with the extension.

**Comment by Dneiz** [comment]
Still no luck, i added the original header cart link content. The mini-cart block is also present. Also, the cart icons graphic, cart count and price are included as well. I see the gray line only when you click on cart again.

What is going wrong?

--- 
**Update**: It looks like working, however, the "cartpopup" container is now showing up on the bottom of the page.

**Comment by Dneiz** [comment]
All working fine. Thank you.
