### ISSUE TITLE
Configurable product

### ISSUE THREAD

**Issue by robertanfortes** [husseycoding/ajaxcartpopup#6]
Hi there.

Great work with this extension!

One doubt, when i choose a configurable product the popoup didn't show up and the product page appears, is that right? I thought that i could be able to buy a configurable product also, and in this case, i could choose the product's attributes at the popup.

Thanks!

**Comment by husseycoding** [comment]
Glad you are finding the extension useful.

For the behaviour you describe, yes that's by design.  On category pages if selections have to be made to be able to add a product to the cart you are redirected to the product page.  When clicking add to cart on the product page after having made your selections you will get the AJAX add to cart behaviour.  We don't have any plans to change this behaviour.
